openapi: 3.0.1
info:
  title: OpenAPI definition
  version: v0
servers:
  - url: http://localhost:3001
    description: Generated server url
security:
  - bearerAuth: []
paths:
  /api/rentals/{id}:
    get:
      tags:
        - Rentals
      operationId: getRentalById
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/RentalDTO'
    put:
      tags:
        - Rentals
      operationId: updateRental
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int32
        - name: name
          in: query
          required: true
          schema:
            type: string
        - name: surface
          in: query
          required: true
          schema:
            type: number
            format: double
        - name: price
          in: query
          required: true
          schema:
            type: number
            format: double
        - name: description
          in: query
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                picture:
                  type: string
                  format: binary
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: object
                additionalProperties:
                  type: string
    delete:
      tags:
        - Rentals
      operationId: deleteRental
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: object
                additionalProperties:
                  type: string
  /api/rentals:
    get:
      tags:
        - Rentals
      operationId: getRentals
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: object
                additionalProperties:
                  type: array
                  items:
                    $ref: '#/components/schemas/RentalDTO'
    post:
      tags:
        - Rentals
      operationId: createRental
      parameters:
        - name: name
          in: query
          required: true
          schema:
            type: string
        - name: surface
          in: query
          required: true
          schema:
            type: number
            format: double
        - name: price
          in: query
          required: true
          schema:
            type: number
            format: double
        - name: description
          in: query
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                picture:
                  type: string
                  format: binary
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: object
                additionalProperties:
                  type: string
  /api/messages:
    post:
      tags:
        - Messages
      operationId: createMessage
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MessageDTO'
        required: true
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: object
                additionalProperties:
                  type: string
  /api/auth/register:
    post:
      tags:
        - Authentication
      operationId: registerUser
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegistrationRequest'
        required: true
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: object
                additionalProperties:
                  type: string
  /api/auth/login:
    post:
      tags:
        - Authentication
      operationId: createAuthenticationToken
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AuthenticationRequest'
        required: true
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: object
                additionalProperties:
                  type: string
  /api/user/{id}:
    get:
      tags:
        - Users
      operationId: getUserById
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/UserDTO'
  /api/auth/me:
    get:
      tags:
        - Authentication
      operationId: getMe
      parameters:
        - name: Authorization
          in: header
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/UserDTO'
components:
  schemas:
    MessageDTO:
      required:
        - created_at
        - message
        - rental_id
        - user_id
      type: object
      properties:
        id:
          type: integer
          format: int64
        rental_id:
          type: integer
          format: int64
        user_id:
          type: integer
          format: int64
        message:
          maxLength: 2000
          minLength: 0
          type: string
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
    RegistrationRequest:
      required:
        - email
        - name
        - password
      type: object
      properties:
        email:
          type: string
        name:
          type: string
        password:
          maxLength: 64
          minLength: 6
          type: string
    AuthenticationRequest:
      required:
        - email
        - password
      type: object
      properties:
        email:
          type: string
        password:
          maxLength: 64
          minLength: 6
          type: string
    UserDTO:
      required:
        - created_at
        - email
        - name
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        email:
          type: string
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
    RentalDTO:
      required:
        - created_at
        - name
        - owner_id
        - price
        - surface
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          maxLength: 64
          minLength: 1
          type: string
        surface:
          type: number
          format: double
        price:
          type: number
          format: double
        picture:
          type: string
        description:
          maxLength: 2000
          minLength: 0
          type: string
        owner_id:
          type: integer
          format: int64
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
  securitySchemes:
    bearerAuth:
      type: http
      name: bearerAuth
      scheme: bearer
      bearerFormat: JWT
