spring:
  application:
    name: backend
  datasource:
    url: jdbc:mysql://${APP_DB_HOST}:${APP_DB_PORT}/${APP_DB_NAME}
    username: ${APP_DB_USER}
    password: ${APP_DB_PASS}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
      # properties:
        # hibernate:
          # dialect: org.hibernate.dialect.MySQL5Dialect
        # enable_lazy_load_no_trans: true
server:
  port: 3001
